hello: test
	@echo "hello world"

test:
	@echo "test"
# 定义：
# targets: prerequisites ; command1
# '\t' command2
#
# @ 不回显字符 
#
# targets prerequisites 可以对个用空格隔开
# 
# 依赖规则：
# 1. 当目标对应的文件不存在，执行相应命令
# 2. 当依赖在时间上比目标更新，执行对应命令
# 3. 当依赖关系连续发生的时候，对比依赖链的每一个目标
